import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { probe } from "../src/ffmpeg/probe.js";
import { trimTool } from "../src/tools/trim.js";
import { convertTool } from "../src/tools/convert.js";
import { extractAudioTool } from "../src/tools/extract.js";
import { thumbnailTool } from "../src/tools/thumbnail.js";
import { concatTool } from "../src/tools/concat.js";

/**
 * End-to-end tests against the real ffmpeg binary. The fixture is generated by
 * ffmpeg itself (lavfi sources) so no external assets are required.
 */

let dir: string;
let fixture: string;

beforeAll(() => {
  dir = mkdtempSync(join(tmpdir(), "ffmpeg-mcp-test-"));
  fixture = join(dir, "fixture.mp4");
  // 5s 320x240 test pattern + 5s sine tone, both encoded.
  execFileSync(
    "ffmpeg",
    [
      "-y",
      "-f", "lavfi", "-i", "testsrc=duration=5:size=320x240:rate=25",
      "-f", "lavfi", "-i", "sine=frequency=440:duration=5",
      "-c:v", "libx264", "-pix_fmt", "yuv420p",
      "-c:a", "aac", "-shortest",
      fixture,
    ],
    { stdio: "ignore" },
  );
});

afterAll(() => {
  rmSync(dir, { recursive: true, force: true });
});

describe("probe", () => {
  it("reports duration and streams", async () => {
    const r = await probe(fixture);
    expect(r.durationSeconds).toBeGreaterThan(4.5);
    expect(r.streams.find((s) => s.type === "video")).toBeTruthy();
    expect(r.streams.find((s) => s.type === "audio")).toBeTruthy();
  });
});

describe("trim", () => {
  it("cuts a 2s segment", async () => {
    const out = join(dir, "trim.mp4");
    await trimTool.handler({ input: fixture, output: out, start: "1", duration: "2", reencode: true, overwrite: true });
    expect(existsSync(out)).toBe(true);
    const r = await probe(out);
    expect(r.durationSeconds).toBeGreaterThan(1.5);
    expect(r.durationSeconds).toBeLessThan(2.6);
  });
});

describe("convert", () => {
  it("scales to 160x120", async () => {
    const out = join(dir, "small.mp4");
    await convertTool.handler({ input: fixture, output: out, resolution: "160x120", overwrite: true });
    const r = await probe(out);
    const v = r.streams.find((s) => s.type === "video")!;
    expect(v.width).toBe(160);
    expect(v.height).toBe(120);
  });
});

describe("extract_audio", () => {
  it("produces an mp3", async () => {
    const out = join(dir, "audio.mp3");
    await extractAudioTool.handler({ input: fixture, output: out, format: "mp3", overwrite: true });
    const r = await probe(out);
    expect(r.streams.find((s) => s.type === "audio")).toBeTruthy();
    expect(r.streams.find((s) => s.type === "video")).toBeFalsy();
  });
});

describe("thumbnail", () => {
  it("captures a single frame", async () => {
    const out = join(dir, "thumb.jpg");
    await thumbnailTool.handler({ input: fixture, output: out, at: "2", overwrite: true });
    expect(existsSync(out)).toBe(true);
  });
});

describe("concat", () => {
  it("joins two copies (stream copy)", async () => {
    const out = join(dir, "joined.mp4");
    await concatTool.handler({ inputs: [fixture, fixture], output: out, mode: "copy", overwrite: true });
    const r = await probe(out);
    expect(r.durationSeconds).toBeGreaterThan(9);
  });
});
